# Auto-generated by state\1_Split_AppState.ps1.
# Do not edit this file directly. Edit the matching source part and rerun the
# assembly script produced by a future refactor phase.
from __future__ import annotations
# Logical section: 02_auth_security

def set_reg_username(self, value: str) -> None:
        self.reg_username = value




    def set_reg_password(self, value: str) -> None:
        self.reg_password = value




    def set_reg_confirm_password(self, value: str) -> None:
        self.reg_confirm_password = value




    def set_reg_totp_code(self, value: str) -> None:
        self.reg_totp_code = value




    def toggle_reg_enable_totp(self, checked: bool) -> None:
        self.reg_enable_totp = checked




    def toggle_show_reg_password(self) -> None:
        self.show_reg_password = not self.show_reg_password




    def toggle_show_reg_confirm_password(self) -> None:
        self.show_reg_confirm_password = not self.show_reg_confirm_password




    def submit_registration(self) -> None:
        if not self.reg_username.strip():
            self.reg_error = "Username is required."
            return
        if len(self.reg_password) < 4:
            self.reg_error = "Password must be at least 4 characters."
            return
        if self.reg_password != self.reg_confirm_password:
            self.reg_error = "Passwords do not match."
            return
        if not _engine.register_credentials(self.reg_username, self.reg_password):
            self.reg_error = "Registration failed. Check your username/password and try again."
            return
        self.reg_error = ""
        if self.reg_enable_totp:
            self.reg_qr_data_uri = _engine.security.begin_totp_enrollment(self.reg_username)
            self.reg_stage = "qr"
        else:
            if _engine.finish_registration_without_totp(self.reg_username, self.reg_password):
                self.totp_required = False
                self._pick_transition_effect()
                self.screen = _engine.screen.value




    def confirm_totp_setup(self) -> None:
        if not self.reg_totp_code.strip():
            self.reg_error = "Enter the 6-digit code from your authenticator app."
            return
        if _engine.finish_registration_with_totp(self.reg_username, self.reg_password, self.reg_totp_code):
            self.reg_error = ""
            self.totp_required = True
            self._pick_transition_effect()
            self.screen = _engine.screen.value
        else:
            self.reg_error = "Incorrect code. Please check your authenticator app and try again."




    def skip_totp_setup(self) -> None:
        self.reg_enable_totp = False
        if _engine.finish_registration_without_totp(self.reg_username, self.reg_password):
            self.totp_required = False
            self._pick_transition_effect()
            self.screen = _engine.screen.value




    def go_to_login(self) -> None:
        self._pick_transition_effect()
        self.screen = _engine.go_to_login().value




    def go_to_register(self) -> None:
        self.reg_username = ""
        self.reg_password = ""
        self.reg_confirm_password = ""
        self.reg_enable_totp = False
        self.reg_error = ""
        self.reg_stage = "form"
        self.reg_qr_data_uri = ""
        self.reg_totp_code = ""
        self._pick_transition_effect()
        self.screen = _engine.go_to_register().value




    def set_login_username(self, value: str) -> None:
        self.login_username = value
        self.login_credentials_match = _engine.security.auth.verify(self.login_username, self.login_password)




    def set_login_password(self, value: str) -> None:
        self.login_password = value
        self.login_credentials_match = _engine.security.auth.verify(self.login_username, self.login_password)




    def set_login_totp(self, value: str) -> None:
        self.login_totp = value




    def toggle_show_login_password(self) -> None:
        self.show_login_password = not self.show_login_password




    def toggle_show_lock_password(self) -> None:
        self.show_lock_password = not self.show_lock_password




    def toggle_login_remember_device(self, checked: bool) -> None:
        self.login_remember_device = checked




    def submit_login(self) -> None:
        if not self.login_username.strip() or len(self.login_password) < 4:
            self.login_error = "Enter your username and password."
            self.login_error_seq += 1
            return self.play_sound("error")
        ok = _engine.attempt_login(self.login_username, self.login_password, self.login_totp or None, self.login_remember_device)
        if ok:
            self.login_error = ""
            self.login_password = ""
            self.login_totp = ""
            self.login_remember_device = False
            self.login_credentials_match = False
            self._pick_transition_effect()
            self.screen = _engine.screen.value
        else:
            self.login_error = "Invalid credentials or authenticator code."
            self.login_error_seq += 1
            return self.play_sound("error")




    def lock_app(self) -> None:
        _engine.lock()
        self._pick_transition_effect()
        self.screen = _engine.screen.value
        self.is_locked = True




    def unlock_app(self) -> None:
        if len(self.login_password) < 4:
            self.login_error = "Password must be at least 4 characters."
            return
        ok = _engine.unlock(self.login_password, self.login_totp or None)
        if ok:
            self.login_error = ""
            self.login_password = ""
            self.login_totp = ""
            self._pick_transition_effect()
            self.screen = _engine.screen.value
            self.is_locked = False
        else:
            self.login_error = "Invalid credentials or authenticator code."




    def begin_manage_security(self) -> None:
        self.manage_username = ""
        self.manage_password = ""
        self.manage_error = ""
        self.manage_stage = "verify"
        self.manage_totp_qr = ""
        self.manage_totp_code = ""
        self.tg_bot_token = ""
        self.tg_chat_id = ""
        self.tg_enabled = _engine.security.is_telegram_enabled()
        self.tg_configured = _engine.manage_is_telegram_configured()
        self.tg_message = ""
        self.dc_webhook_url = ""
        self.dc_enabled = _engine.security.is_discord_enabled()
        self.dc_configured = _engine.manage_is_discord_configured()
        self.dc_message = ""
        self.totp_required = _engine.security.is_totp_enabled()
        self._pick_transition_effect()
        self.screen = _engine.begin_manage_security().value




    def set_manage_username(self, value: str) -> None:
        self.manage_username = value




    def set_manage_password(self, value: str) -> None:
        self.manage_password = value




    def toggle_show_manage_password(self) -> None:
        self.show_manage_password = not self.show_manage_password




    def verify_manage_identity(self) -> None:
        if _engine.verify_manage_security_identity(self.manage_username, self.manage_password):
            self.manage_error = ""
            self.manage_stage = "panel"
            self.totp_required = _engine.security.is_totp_enabled()
        else:
            self.manage_error = "Incorrect username or password."




    def start_enable_totp(self) -> None:
        self.manage_totp_qr = _engine.manage_totp_begin_enable(self.manage_username)
        self.manage_stage = "totp_qr"




    def set_manage_totp_code(self, value: str) -> None:
        self.manage_totp_code = value




    def confirm_enable_totp(self) -> None:
        if not self.manage_totp_code.strip():
            self.manage_error = "Enter the 6-digit code from your authenticator app."
            return
        if _engine.manage_totp_confirm_enable(self.manage_totp_code):
            self.manage_error = ""
            self.manage_stage = "panel"
            self.totp_required = True
        else:
            self.manage_error = "Incorrect code. Please try again."




    def disable_totp(self) -> None:
        _engine.manage_totp_disable()
        self.totp_required = False




    def set_tg_bot_token(self, value: str) -> None:
        self.tg_bot_token = value




    def set_tg_chat_id(self, value: str) -> None:
        self.tg_chat_id = value




    def toggle_tg_enabled(self, checked: bool) -> None:
        self.tg_enabled = checked




    def save_telegram(self) -> None:
        _engine.manage_save_telegram(self.tg_bot_token, self.tg_chat_id, self.tg_enabled)
        self.tg_configured = _engine.manage_is_telegram_configured()
        self.tg_bot_token = ""
        self.tg_message = "Saved." if self.tg_configured else "Saved, but no bot token/chat ID is on file yet - enter both once."




    def test_telegram(self) -> None:
        success, detail = _engine.manage_test_telegram()
        self.tg_message = detail




    def set_dc_webhook_url(self, value: str) -> None:
        self.dc_webhook_url = value




    def toggle_dc_enabled(self, checked: bool) -> None:
        self.dc_enabled = checked




    def save_discord(self) -> None:
        _engine.manage_save_discord(self.dc_webhook_url, self.dc_enabled)
        self.dc_configured = _engine.manage_is_discord_configured()
        self.dc_webhook_url = ""
        self.dc_message = "Saved." if self.dc_configured else "Saved, but no webhook URL is on file yet - enter one once."




    def test_discord(self) -> None:
        success, detail = _engine.manage_test_discord()
        self.dc_message = detail




    def finish_manage_security(self) -> None:
        self._pick_transition_effect()
        self.screen = _engine.finish_manage_security().value




    def begin_forgot_password(self) -> None:
        self.forgot_selected_method = ""
        self.forgot_code = ""
        self.forgot_otp_sent = False
        self.forgot_verified = False
        self.forgot_new_password = ""
        self.forgot_confirm_password = ""
        self.forgot_error = ""
        self.forgot_has_any_method = _engine.has_any_recovery_method()
        self.forgot_available_methods = _engine.available_reset_methods()
        self.forgot_stage = "reset" if not self.forgot_has_any_method else "choose"
        self._pick_transition_effect()
        self.screen = _engine.begin_forgot_password().value




    def cancel_forgot_password(self) -> None:
        self.forgot_new_password = ""
        self.forgot_confirm_password = ""
        self.forgot_error = ""
        self._pick_transition_effect()
        self.screen = _engine.cancel_forgot_password().value




    def select_forgot_method(self, method: str) -> None:
        self.forgot_selected_method = method
        self.forgot_error = ""
        if method == "totp":
            self.forgot_stage = "enter_code"
        else:
            if _engine.send_forgot_otp(method):
                self.forgot_otp_sent = True
                self.forgot_stage = "enter_code"
            else:
                self.forgot_error = f"Could not send a code via {method.title()}. Check the channel configuration in Manage Account Security."




    def resend_forgot_otp(self) -> None:
        if self.forgot_selected_method in ("telegram", "discord"):
            _engine.send_forgot_otp(self.forgot_selected_method)
            self.forgot_otp_sent = True




    def set_forgot_code(self, value: str) -> None:
        self.forgot_code = value




    def verify_forgot_identity(self) -> None:
        if not self.forgot_code.strip():
            self.forgot_error = "Enter the code."
            return
        if _engine.verify_identity_for_reset(self.forgot_selected_method, self.forgot_code):
            self.forgot_error = ""
            self.forgot_verified = True
            self.forgot_stage = "reset"
        else:
            self.forgot_error = "That code did not match. Double-check and try again."




    def set_forgot_new_password(self, value: str) -> None:
        self.forgot_new_password = value




    def set_forgot_confirm_password(self, value: str) -> None:
        self.forgot_confirm_password = value




    def toggle_show_forgot_new_password(self) -> None:
        self.show_forgot_new_password = not self.show_forgot_new_password




    def toggle_show_forgot_confirm_password(self) -> None:
        self.show_forgot_confirm_password = not self.show_forgot_confirm_password




    def submit_new_password(self) -> None:
        if len(self.forgot_new_password) < 4:
            self.forgot_error = "Password must be at least 4 characters."
            return
        if self.forgot_new_password != self.forgot_confirm_password:
            self.forgot_error = "Passwords do not match."
            return
        if self.forgot_verified:
            ok = _engine.reset_password(self.forgot_new_password)
        else:
            ok = _engine.reset_password_unverified(self.forgot_new_password)
        if ok:
            self.forgot_error = ""
            self._pick_transition_effect()
            self.screen = _engine.screen.value
        else:
            self.forgot_error = "Could not reset password. Please try again."




    def open_logout_dialog(self) -> None:
        self.logout_stage = "trade_choice" if _engine.has_open_trades() else "confirm"
        self.show_logout_dialog = True




    def close_logout_dialog(self) -> None:
        self.show_logout_dialog = False




    def _do_logout(self, close_trades: bool | None) -> None:
        self._pick_transition_effect()
        self.screen = _engine.logout(close_trades).value
        self.show_logout_dialog = False
        self.login_username = ""
        self.login_password = ""
        self.login_totp = ""
        self.login_error = ""
        self.login_credentials_match = False




    def confirm_logout_no_trades(self) -> None:
        self._do_logout(None)




    def confirm_logout_close_trades(self) -> None:
        self._do_logout(True)




    def confirm_logout_keep_trades(self) -> None:
        self._do_logout(False)

