# Auto-generated by state\1_Split_AppState.ps1.
# Do not edit this file directly. Edit the matching source part and rerun the
# assembly script produced by a future refactor phase.
from __future__ import annotations
# Logical section: 05_trading_panel

def _chart_workspace_key(self, symbol: str, tf: str) -> str:
        return f"chart_display_days::{symbol}::{tf}"



    def _load_trading_panel_display_days(self) -> None:
        saved = _engine.security.persistence.load().get(
            self._chart_workspace_key(self.trading_panel_symbol, self.trading_panel_chart_tf)
        )
        self.trading_panel_display_days_input = str(saved) if saved else "5"



    def set_trading_panel_symbol(self, value: str) -> None:
        self.trading_panel_symbol = value
        self._load_trading_panel_display_days()
        self.refresh_trading_panel_chart()



    def set_trading_panel_chart_tf(self, value: str) -> None:
        self.trading_panel_chart_tf = value
        self._load_trading_panel_display_days()
        self.refresh_trading_panel_chart()



    def set_trading_panel_display_days(self, value: str) -> None:
        """Never silently calls the broker - only changes how many *locally
        available* days are rendered. If X > A, refresh_trading_panel_chart()
        surfaces a notice instead of fetching anything."""
        self.trading_panel_display_days_input = value
        try:
            days = int(value)
            if days <= 0:
                self.trading_panel_notice = "Enter a positive whole number of days."
                return
        except ValueError:
            self.trading_panel_notice = "Enter a positive whole number of days."
            return
        _engine.security.persistence.save({
            self._chart_workspace_key(self.trading_panel_symbol, self.trading_panel_chart_tf): days
        })
        self.refresh_trading_panel_chart()



    def set_trading_panel_chart_theme(self, value: str) -> None:
        """Chart-local only - never touches the app-wide theme_key.
        NOT YET WIRED into react-klinecharts' `styles` prop - the exact
        Styles shape for candle up/down colors wasn't confirmed against
        the library docs, so this is currently just persisted state
        without a visual effect. Flagged as a follow-up, not silently
        dropped."""
        self.trading_panel_chart_theme = value
        _engine.security.persistence.save({"trading_panel_chart_theme": value})



    def refresh_trading_panel_chart(self) -> None:
        try:
            requested_days = int(self.trading_panel_display_days_input)
        except ValueError:
            requested_days = 5

        progress = _engine.market_data.get_deep_history_progress(
            self.trading_panel_symbol, self.trading_panel_chart_tf
        )
        local_days = progress["covered_days"]
        self.trading_panel_local_days = str(local_days)

        ceiling = _engine.market_data.get_ceiling_days(self.trading_panel_symbol, self.trading_panel_chart_tf)
        self.trading_panel_broker_days = f"{ceiling} days" if ceiling is not None else "Not checked yet"

        effective_days = min(requested_days, local_days) if local_days else requested_days
        if local_days and requested_days > local_days:
            self.trading_panel_notice = f"{requested_days} days requested \u2022 {local_days} days available locally"
        elif not local_days:
            self.trading_panel_notice = "No local historical coverage yet for this symbol/timeframe."
        else:
            self.trading_panel_notice = ""

        candles = _engine.market_data.get_chart_candles(
            self.trading_panel_symbol,
            self.trading_panel_chart_tf,
            effective_days,
        )
        live = None



        # ASSUMPTION FLAGGED: Candle fields assumed to be open/high/low/close/open_time.
        # Confirm against candle_builder_worker.py's real Candle dataclass before running.
        # Volume is NOT confirmed available on Candle - defaulted to 0.0 here.
        # Row keys match react-klinecharts' KLineData shape directly (timestamp/open/high/low/close/volume).
        rows = [
            {
                "timestamp": c.open_time,
                "open": float(c.open),
                "high": float(c.high),
                "low": float(c.low),
                "close": float(c.close),
                "volume": float(c.volume),
            }
            for c in candles
        ]   


        
        self.trading_panel_candles = rows

        current = live or (candles[-1] if candles else None)
        if current:
            self.trading_panel_current_open = f"{current.open:,.2f}"
            self.trading_panel_current_high = f"{current.high:,.2f}"
            self.trading_panel_current_low = f"{current.low:,.2f}"
            self.trading_panel_current_close = f"{current.close:,.2f}"
        else:
            self.trading_panel_current_open = self.trading_panel_current_high = \
                self.trading_panel_current_low = self.trading_panel_current_close = "--"


    @rx.event(background=True)

    async def poll_trading_panel_chart(self):
        """Same guarded-loop pattern as poll_ws_status/poll_pinned_prices.
        KNOWN SIMPLIFICATION: does not stop when the user leaves the Trading
        Panel tab - deliberately deferred, not an oversight."""
        async with self:
            if self._trading_panel_poll_running:
                return
            self._trading_panel_poll_running = True
        try:
            while True:
                async with self:
                    self.refresh_trading_panel_chart()
                await asyncio.sleep(3)
        finally:
            async with self:
                self._trading_panel_poll_running = False




    def trading_panel_symbol_options(self) -> list[str]:
        return _engine.market_data.symbol_registry.get_symbols_sorted(active_only=True)



    @rx.var

    def trading_panel_symbol_info(self) -> dict:
        """Shape expected by <KLineChart symbol={...}>: {ticker, precision}.
        precision (decimal places) is derived from the real tick_size on
        SymbolRegistryWorker - falls back to 2 if the symbol isn't found."""
        registry = _engine.market_data.symbol_registry
        info = registry.get_symbol_info(self.trading_panel_symbol)
        if info is None or not info.tick_size:
            return {"ticker": self.trading_panel_symbol, "precision": 2}
        tick = info.tick_size
        precision = 0
        while round(tick, precision) != tick and precision < 8:
            precision += 1
        return {"ticker": self.trading_panel_symbol, "precision": precision}



    @rx.var

    def trading_panel_period(self) -> dict:
        return TRADING_PANEL_PERIOD_MAP.get(self.trading_panel_chart_tf, TRADING_PANEL_PERIOD_MAP["5m"])

