# Auto-generated by state\1_Split_AppState.ps1.
# Do not edit this file directly. Edit the matching source part and rerun the
# assembly script produced by a future refactor phase.
from __future__ import annotations
# Logical section: 01_core_shell

def on_load(self) -> None:
        self.theme_key = _engine.ui.theme.get_active_key()
        self.paper_mode = _engine.paper_mode
        self.sound_muted = not _engine.ui.sound.is_master_on()
        settings = _engine.security.persistence.load()
        self.transition_effects_enabled = settings.get("transition_effects_enabled", self.transition_effects_enabled)
        self.transition_mode = settings.get("transition_mode", self.transition_mode)
        self.tab_transition_effects_enabled = settings.get("tab_transition_effects_enabled", self.tab_transition_effects_enabled)
        self.tab_transition_mode = settings.get("tab_transition_mode", self.tab_transition_mode)
        self.trading_panel_chart_theme = settings.get("trading_panel_chart_theme", self.trading_panel_chart_theme)
        _engine.ensure_market_data_started()
        self.refresh_symbol_rows()
        return AppState.start_poi_monitor_background



    @rx.event(background=True)

    async def start_poi_monitor_background(self):
        """POIMonitor's construction makes many blocking network calls
        (every active symbol x every POI Worker type x up to 8 timeframes).
        Running it via asyncio.to_thread() offloads that blocking work to a
        separate OS thread so it never freezes the shared asyncio event
        loop the rest of the app depends on."""
        async with self:
            if self._poi_monitor_starting:
                return
            self._poi_monitor_starting = True
        try:
            await asyncio.to_thread(_engine.ensure_poi_monitor_started)
            async with self:
                self.load_poi_settings()
        finally:
            async with self:
                self._poi_monitor_starting = False




    async def run_splash_sequence(self):
        """Fires the bar-fill animation fresh via rx.call_script, waits the fill duration,
        holds at 100%, then dissolves to Register/Login (hardcoded, never the random pool).
        Guarded against React Strict Mode's double-invocation of on_mount - see module docstring.
        """
        if self._splash_task_running:
            return
        self._splash_task_running = True
        try:
            duration_ms = int(SPLASH_DURATION_SECONDS * 1000)
            yield rx.call_script(
                f"""
                (function() {{
                    const fill = document.getElementById('qt19-splash-bar-fill');
                    const pct = document.getElementById('qt19-splash-pct');
                    if (fill) {{
                        fill.style.transition = 'none';
                        fill.style.transform = 'scaleX(0)';
                        void fill.offsetWidth;
                        fill.style.transition = 'transform {SPLASH_DURATION_SECONDS}s linear';
                        requestAnimationFrame(function() {{ fill.style.transform = 'scaleX(1)'; }});
                    }}
                    if (pct) {{ pct.textContent = '0%'; }}
                    const start = Date.now();
                    const durationMs = {duration_ms};
                    const interval = setInterval(function() {{
                        const elapsed = Date.now() - start;
                        const percent = Math.min(100, Math.round((elapsed / durationMs) * 100));
                        if (pct) {{ pct.textContent = percent + '%'; }}
                        if (elapsed >= durationMs) {{ clearInterval(interval); }}
                    }}, 100);
                }})();
                """
            )
            await asyncio.sleep(SPLASH_DURATION_SECONDS)
            await asyncio.sleep(SPLASH_HOLD_SECONDS)
            self.totp_required = _engine.security.is_totp_enabled() and not _engine.security.is_device_trusted()
            self.transition_active_effect = "dissolve"
            self.screen = _engine.finish_splash().value
        finally:
            self._splash_task_running = False




    def _pick_transition_effect(self) -> None:
        effect, next_index = _engine.ui.transitions.pick(
            self.transition_effects_enabled, self.transition_mode, self._transition_sequence_index
        )
        self.transition_active_effect = effect
        self._transition_sequence_index = next_index




    def _pick_tab_transition_effect(self) -> None:
        effect, next_index = _engine.ui.transitions.pick(
            self.tab_transition_effects_enabled, self.tab_transition_mode, self._tab_transition_sequence_index
        )
        self.tab_transition_active_effect = effect
        self._tab_transition_sequence_index = next_index




    def set_active_tab(self, tab: str) -> None:
        self.active_tab = tab
        self.detail_popup_open = False
        self._pick_tab_transition_effect()
        if tab == "Trading Panel":
            self.refresh_trading_panel_chart()
            return [self.play_sound("tab-slide"), AppState.poll_trading_panel_chart]
        return self.play_sound("tab-slide")




    def set_theme(self, key: str) -> None:
        if _engine.ui.theme.set_active_key(key):
            self.theme_key = key




    def toggle_sound(self) -> None:
        is_on = _engine.ui.sound.toggle_master()
        self.sound_muted = not is_on




    def play_sound(self, event_name: str):
        url = _engine.ui.play_sound(event_name)
        if not url:
            return
        return rx.call_script(
            f"(function(){{ try {{ new Audio('{url}').play().catch(function(){{}}); }} "
            f"catch(e) {{}} }})();"
        )



    @rx.event(background=True)

    def toggle_transition_effect(self, effect: str, checked: bool) -> None:
        current = list(self.transition_effects_enabled)
        if checked and effect not in current:
            current.append(effect)
        elif not checked and effect in current:
            current.remove(effect)
        if not current:
            current = [effect]
        self.transition_effects_enabled = current
        _engine.security.persistence.save({"transition_effects_enabled": current})




    def set_transition_mode(self, mode: str) -> None:
        self.transition_mode = mode
        _engine.security.persistence.save({"transition_mode": mode})




    def toggle_tab_transition_effect(self, effect: str, checked: bool) -> None:
        current = list(self.tab_transition_effects_enabled)
        if checked and effect not in current:
            current.append(effect)
        elif not checked and effect in current:
            current.remove(effect)
        if not current:
            current = [effect]
        self.tab_transition_effects_enabled = current
        _engine.security.persistence.save({"tab_transition_effects_enabled": current})




    def set_tab_transition_mode(self, mode: str) -> None:
        self.tab_transition_mode = mode
        _engine.security.persistence.save({"tab_transition_mode": mode})



    @rx.var

    def theme_vars(self) -> dict[str, str]:
        t = THEMES[self.theme_key]
        return {
            "accent": t.accent, "accent_glow": t.accent_glow, "bg_from": t.bg_from, "bg_to": t.bg_to,
            "glass_bg": t.glass_bg, "glass_border": t.glass_border,
            "text_primary": t.text_primary, "text_muted": t.text_muted,
        }



    @rx.var

    def sidebar_tabs(self) -> list[str]:
        return SIDEBAR_TABS



    @rx.var

    def theme_options(self) -> list[dict[str, str]]:
        return [{"key": k, "label": THEME_LABELS[k]} for k in THEME_ORDER]



    @rx.var

    def transition_effect_options(self) -> list[dict[str, str]]:
        return [{"key": k, "label": v} for k, v in TRANSITION_EFFECTS.items()]



    @rx.var

